controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# NelmioApiDocBundle routes
nelmio_api_doc:
    resource: '@NelmioApiDocBundle/config/routing/swaggerui.xml'
    prefix: /api/doc
